use crate::policy::{Channel, Kind};

fn default_channel(channels: &[Channel]) -> Channel {
    if channels.contains(&Channel::DeveloperId) {
        Channel::DeveloperId
    } else {
        channels[0]
    }
}

pub fn render(kind: Kind, channels: &[Channel]) -> String {
    let toolchain = match kind {
        Kind::Gpui => GPUI_STEPS,
        Kind::Tauri => TAURI_STEPS,
        Kind::Native => NATIVE_STEPS,
    };
    let runner = match kind {
        Kind::Native => "macos-15",
        Kind::Gpui | Kind::Tauri => "macos-latest",
    };
    let default = default_channel(channels);
    let secrets = SECRETS.replace(
        "github.event.inputs.channel || 'developer-id'",
        &format!("github.event.inputs.channel || '{default}'"),
    );
    format!(
        "{header}{secrets}    runs-on: {runner}\n{toolchain}{footer}",
        header = header(channels),
        footer = footer(channels),
    )
}

fn header(channels: &[Channel]) -> String {
    let default = default_channel(channels);
    let options = channels
        .iter()
        .map(|c| format!("          - {c}"))
        .collect::<Vec<_>>()
        .join("\n");
    let tags = if channels.contains(&Channel::DeveloperId) {
        "  push:\n    tags:\n      - \"v*\"\n"
    } else {
        ""
    };
    format!(
        r#"# Generated by apple-ship setup. Re-run setup to refresh.
name: macOS Ship

on:
  workflow_dispatch:
    inputs:
      channel:
        description: Signing channel
        type: choice
        options:
{options}
        default: {default}
{tags}
permissions:
  contents: write

jobs:
  ship:
    name: Ship macOS
"#
    )
}

fn footer(channels: &[Channel]) -> String {
    let release = if channels.contains(&Channel::DeveloperId) {
        r#"      - name: GitHub Release
        if: startsWith(github.ref, 'refs/tags/') && env.CHANNEL == 'developer-id'
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ steps.ship.outputs.artifact }}
          generate_release_notes: true
          fail_on_unmatched_files: true
"#
    } else {
        ""
    };
    format!("{FOOTER_CORE}{release}")
}

const SECRETS: &str = r#"    environment: release
    env:
      CHANNEL: ${{ github.event.inputs.channel || 'developer-id' }}
      APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
      APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      APPLE_CERTIFICATE_APP_STORE: ${{ secrets.APPLE_CERTIFICATE_APP_STORE }}
      APPLE_CERTIFICATE_APP_STORE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_APP_STORE_PASSWORD }}
      APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      APPLE_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
      APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
      APPLE_API_KEY_P8: ${{ secrets.APPLE_API_KEY_P8 }}
"#;

const GPUI_STEPS: &str = r#"    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Metal toolchain
        run: xcodebuild -downloadComponent MetalToolchain
      - name: Install apple-ship
        run: cargo install apple-ship --git https://github.com/meritozh/apple-ship --locked
"#;

const TAURI_STEPS: &str = r#"    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile
      - name: Install apple-ship
        run: cargo install apple-ship --git https://github.com/meritozh/apple-ship --locked
"#;

const NATIVE_STEPS: &str = r#"    steps:
      - uses: actions/checkout@v5
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26"
      - name: Install apple-ship
        run: cargo install apple-ship --git https://github.com/meritozh/apple-ship --locked
"#;

const FOOTER_CORE: &str = r#"      - name: Ship
        id: ship
        run: apple-ship ci --channel "$CHANNEL"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ env.CHANNEL }}
          path: ${{ steps.ship.outputs.artifact }}
          if-no-files-found: error
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gpui_developer_id_workflow() {
        let yaml = render(Kind::Gpui, &[Channel::DeveloperId]);
        assert!(yaml.contains("environment: release"));
        assert!(yaml.contains("apple-ship ci --channel"));
        assert!(yaml.contains("Metal toolchain"));
        assert!(yaml.contains("workflow_dispatch"));
        assert!(yaml.contains("- developer-id"));
        assert!(!yaml.contains("- app-store"));
        assert!(yaml.contains("push:"));
        assert!(!yaml.contains("setup-xcode"));
    }

    #[test]
    fn app_store_only_has_no_tag_release() {
        let yaml = render(Kind::Gpui, &[Channel::AppStore]);
        assert!(yaml.contains("- app-store"));
        assert!(!yaml.contains("- developer-id"));
        assert!(!yaml.contains("action-gh-release"));
        assert!(!yaml.contains("tags:"));
    }

    #[test]
    fn both_channels_listed() {
        let yaml = render(Kind::Gpui, &[Channel::DeveloperId, Channel::AppStore]);
        assert!(yaml.contains("- developer-id"));
        assert!(yaml.contains("- app-store"));
        assert!(yaml.contains("action-gh-release"));
    }

    #[test]
    fn native_pins_xcode_26() {
        let yaml = render(Kind::Native, &[Channel::DeveloperId]);
        assert!(yaml.contains("macos-15"));
        assert!(yaml.contains("xcode-version: \"26\""));
    }

    #[test]
    fn tauri_installs_frontend() {
        let yaml = render(Kind::Tauri, &[Channel::DeveloperId]);
        assert!(yaml.contains("pnpm install --frozen-lockfile"));
    }
}
