use crate::policy::Kind;

pub fn render(kind: Kind) -> String {
    let toolchain = match kind {
        Kind::Gpui => GPUI_STEPS,
        Kind::Tauri => TAURI_STEPS,
        Kind::Native => NATIVE_STEPS,
    };
    let runner = match kind {
        Kind::Native => "macos-15",
        Kind::Gpui | Kind::Tauri => "macos-latest",
    };
    format!("{HEADER}{SECRETS}    runs-on: {runner}\n{toolchain}{FOOTER}")
}

const HEADER: &str = r#"# Generated by apple-ship. Re-run `apple-ship setup --force` to refresh.
name: macOS Ship

on:
  workflow_dispatch:
    inputs:
      channel:
        description: Signing channel
        type: choice
        options:
          - developer-id
          - app-store
        default: developer-id
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  ship:
    name: Ship macOS
"#;

const SECRETS: &str = r#"    environment: release
    env:
      CHANNEL: ${{ github.event.inputs.channel || 'developer-id' }}
      APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
      APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      APPLE_CERTIFICATE_APP_STORE: ${{ secrets.APPLE_CERTIFICATE_APP_STORE }}
      APPLE_CERTIFICATE_APP_STORE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_APP_STORE_PASSWORD }}
      APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      APPLE_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
      APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
      APPLE_API_KEY_P8: ${{ secrets.APPLE_API_KEY_P8 }}
"#;

const GPUI_STEPS: &str = r#"    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Metal toolchain
        run: xcodebuild -downloadComponent MetalToolchain
      - name: Install apple-ship
        run: cargo install apple-ship --git https://github.com/meritozh/apple-ship --locked
"#;

const TAURI_STEPS: &str = r#"    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile
      - name: Install apple-ship
        run: cargo install apple-ship --git https://github.com/meritozh/apple-ship --locked
"#;

const NATIVE_STEPS: &str = r#"    steps:
      - uses: actions/checkout@v5
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26"
      - name: Install apple-ship
        run: cargo install apple-ship --git https://github.com/meritozh/apple-ship --locked
"#;

const FOOTER: &str = r#"      - name: Ship
        id: ship
        run: apple-ship ci --channel "$CHANNEL"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ env.CHANNEL }}
          path: ${{ steps.ship.outputs.artifact }}
          if-no-files-found: error
      - name: GitHub Release
        if: startsWith(github.ref, 'refs/tags/') && env.CHANNEL == 'developer-id'
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ steps.ship.outputs.artifact }}
          generate_release_notes: true
          fail_on_unmatched_files: true
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gpui_workflow_has_release_env_and_ci() {
        let yaml = render(Kind::Gpui);
        assert!(yaml.contains("environment: release"));
        assert!(yaml.contains("apple-ship ci --channel"));
        assert!(yaml.contains("Metal toolchain"));
        assert!(yaml.contains("workflow_dispatch"));
        assert!(!yaml.contains("setup-xcode"));
    }

    #[test]
    fn native_pins_xcode_26() {
        let yaml = render(Kind::Native);
        assert!(yaml.contains("macos-15"));
        assert!(yaml.contains("xcode-version: \"26\""));
    }

    #[test]
    fn tauri_installs_frontend() {
        let yaml = render(Kind::Tauri);
        assert!(yaml.contains("pnpm install --frozen-lockfile"));
    }
}
